### ISSUE TITLE
Apresentação da Release 1

### ISSUE THREAD

**Issue by micaellagouveia** [fga-eps-mds/2021.1-Multilind-Docs#122]
### Descrição da *issue*
Produção e ensaios da apresentação da Release 1 que acontecerá dia 17/09 às 18h com as clientes.

### Tarefas
- [x] Slides
- [x] Separação das partes
- [x] Ensaios

**Comment by sofiapatrocinio** [comment]
- Organização: scrum e métricas - Igor
-  Lean Inception - Sofia
- Tecnologias: quais tecnologias estamos usando e porquê - Helder e Hérick
- Arquitetura: diagrama de relações - Fael
- Planejamento: análise de custo e de risco - Davi
- Backlog - Micaella
- Protótipo - Ingrid e Sofia
- Implementação - Isadora e Davi

**Comment by sofiapatrocinio** [comment]
Organização
- "Papéis" de cada membro da equipe
- Explicar metodologia ágil
- Métricas gestão do time: quadro de conhecimento, burndown, health check, **retrospectiva**
- Plano de comunicação
- Ferramentas

Lean Inception
- O que é
- Resultado MVP

Tecnologias
- Explicar cada tecnologia/por que estamos usando
- Pipeline
- Integração SonarCloud

Arquitetura
- Microsserviços
- Banco de dados
- Diagrama de relações

Planejamento
- Análise de custos
- Análise de riscos
- Semana entrega MVP

Backlog
- Mostrar backlog
- Justificar corte escopo

Protótipo
- Explicar
- Mostrar Baixa, Média e Alta Fidelidade

Implementação
- Mostrar app rodando
- Falar o que já foi feito
