### ISSUE TITLE
US24 Localização no Mapa

### ISSUE THREAD

**Issue by micaellagouveia** [fga-eps-mds/2021.1-Multilind-Docs#84]
Eu como usuário desejo ver uma região específica do mapa para que eu possa saber as línguas faladas na área

### Tarefas
- [x] Fazer configuração inicial das rotas
- [x] Integralizar mapa

### Critérios de aceitação
- [x] Deve dar ênfase na região selecionada
- [x] Deve permitir interação com o mapa
- [x] Deve mostrar informações gerais sobre a língua
- [x] Deve oferecer a possibilidade de ver mais detalhes
- [x] Testes Unitários

**Comment by GabrielDVpereira** [comment]
Aparentemente o google fez uma atualização em seu serviço de localização que quebrou a api do expo para. Todavia, uma solução já está sendo resolvida por essa issue https://github.com/expo/expo/issues/14248, nós vamos dar ênfase somente em mostrar o mapa  e seus pontos até que liberem uma solução, que deve ser breve
